### ISSUE TITLE
Does not support recent MC

### ISSUE THREAD

**Issue by Anarchick** [hugmanrique/NoWorldSave#2]
Hi, I'm trying to update your code for mc 1.17.1, I have read your tutorial : [https://hugmanrique.me/posts/modifying-nms-from-a-plugin/](https://hugmanrique.me/posts/modifying-nms-from-a-plugin/)

And I have this in my onEnable() (load: STARTUP): 
```java
private void patch() {
		ClassPool cp = ClassPool.getDefault();
		try {
			// Calling string to not init the class
			CtClass ctClass = cp.get("net.minecraft.server.level.ChunkProviderServer");
			CtMethod saveMethod = getMethod(ctClass, "save");
			//saveMethod.setBody("{}");
			saveMethod.setBody("{ System.out.println(\"Trying to save chunk!\"); }");
			ctClass.toClass();
			Logging.info("ChunkProviderServer has been patched");
		} catch (NotFoundException | CannotCompileException e) {
			e.printStackTrace();
		}
	}
	
	private CtMethod getMethod(CtClass ctClass, String name) {
        return Arrays.stream(ctClass.getMethods())
                .filter(method -> method.getName().equals(name))
                .findAny()
                .orElse(null);
    }
```

I have an issue with .toClass() : 
```
[14:51:20 INFO]: [noWorldSave] Loading noWorldSave v1.0
[14:51:20 INFO]: [noWorldSave] Enabling noWorldSave v1.0
> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by javassist.util.proxy.SecurityActions (file:/C:/Users/aeim/Documents/minecraft/btooomJava/plugins/noWorldSave.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of javassist.util.proxy.SecurityActions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[14:51:20 WARN]: javassist.CannotCompileException: by java.lang.reflect.InvocationTargetException
[14:51:20 WARN]:        at noWorldSave.jar//javassist.util.proxy.DefineClassHelper$JavaOther.defineClass(DefineClassHelper.java:220)
[14:51:20 WARN]:        at noWorldSave.jar//javassist.util.proxy.DefineClassHelper$Java11.defineClass(DefineClassHelper.java:52)
[14:51:20 WARN]:        at noWorldSave.jar//javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:260)
[14:51:20 WARN]:        at noWorldSave.jar//javassist.ClassPool.toClass(ClassPool.java:1240)
[14:51:20 WARN]:        at noWorldSave.jar//javassist.ClassPool.toClass(ClassPool.java:1098)
[14:51:20 WARN]:        at noWorldSave.jar//javassist.ClassPool.toClass(ClassPool.java:1056)
[14:51:20 WARN]:        at noWorldSave.jar//javassist.CtClass.toClass(CtClass.java:1298)
[14:51:20 WARN]:        at noWorldSave.jar//fr.anarchick.noworldsave.Main.patch(Main.java:38)
[14:51:20 WARN]:        at noWorldSave.jar//fr.anarchick.noworldsave.Main.onEnable(Main.java:23)
[14:51:20 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:51:20 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:51:20 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:51:20 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[14:51:20 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[14:51:20 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:288)
[14:51:20 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[14:51:20 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[14:51:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[14:51:20 WARN]: Caused by: java.lang.reflect.InvocationTargetException
[14:51:20 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:51:20 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[14:51:20 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:51:20 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[14:51:20 WARN]:        at noWorldSave.jar//javassist.util.proxy.DefineClassHelper$JavaOther.defineClass(DefineClassHelper.java:214)
[14:51:20 WARN]:        ... 17 more
[14:51:20 WARN]: Caused by: java.lang.LinkageError: loader 'app' attempted duplicate class definition for net.minecraft.server.level.ChunkProviderServer. (net.minecraft.server.level.ChunkProviderServer is in unnamed module of loader 'app')
[14:51:20 WARN]:        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[14:51:20 WARN]:        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
[14:51:20 WARN]:        ... 22 more
```

I did something wrong or It's impossible to patch mc1.17.1 at runtime ?

I have also try your other project "CraftPatch" but it does not support Java9+ and I'm not too good with java to add support for JDK16

Thx for your reply

**Comment by Anarchick** [comment]
This code say that the class is already loaded
```java
                java.lang.reflect.Method m = ClassLoader.class.getDeclaredMethod("findLoadedClass", new Class[] { String.class });
		m.setAccessible(true);
	        ClassLoader cl = ClassLoader.getSystemClassLoader();
	        Object test1 = m.invoke(cl, "net.minecraft.server.level.ChunkProviderServer");
	        Boolean b = test1 != null;
	        Logging.info("ChunkProviderServer is loaded ? " + b);
```

**Comment by hugmanrique** [comment]
I haven't touched NMS code in a while, but it's probable that recent versions of Minecraft load world-related classes before CraftBukkit has a chance to load plugins. This means that the approach in the blog post no longer works, and a lower-level method like loading a class redefinition agent (a quick search yielt this [page](https://github.com/turn/RedefineClassAgent)) might work.

Let me know if you get it working, I could update the post if so :)
